- name: Test playbook
  hosts: node
  vars:
    node: 3.252.196.75

  tasks:
  - ansible.builtin.shell: |
      apt-get update &&
      apt-get upgrade -y &&
      apt-get clean
      stress --cpu 8 --timeout 800
