- name: Test playbook
  hosts: all

  tasks:
  - name: Pause task
    ansible.builtin.pause:
      minutes: 1440
  
  # - ansible.builtin.shell: |
  #     sudo yum update &&
  #     sudo yum upgrade -y &&
  #     sudo yum install stress -y &&
  #     stress --cpu 8 --timeout {{ timeout }}
