- name: Test playbook
  hosts: all

  tasks:
  - ansible.builtin.shell: |
      sudo yum update &&
      sudo yum upgrade -y &&
      sudo yum install stress -y &&
      stress --cpu 8 --timeout {{ timeout }}
